/**
 * Moderation console.
 *
 * There is deliberately NO login form here. Access is enforced by Cloudflare Access
 * (Zero Trust) in front of /admin/* and the API verifies the Cf-Access-Jwt-Assertion
 * header server-side. A hand-rolled admin login on a site that holds sick people's
 * contact details is not a risk worth taking.
 */

export function admin() {
  const body = `
<section class="page-head">
  <div class="wrap">
    <p class="eyebrow">Internal</p>
    <h1>Moderation console</h1>
    <p class="muted" data-admin-identity>Checking access&hellip;</p>
  </div>
</section>

<section class="section">
  <div class="wrap">
    <div class="admin-stats" data-admin-stats></div>

    <div class="tabs" role="tablist">
      <button class="tab is-active" role="tab" data-tab="stories" aria-selected="true">
        Stories <span class="badge" data-badge="stories">0</span>
      </button>
      <button class="tab" role="tab" data-tab="social" aria-selected="false">
        Social queue <span class="badge" data-badge="social">0</span>
      </button>
      <button class="tab" role="tab" data-tab="signatures" aria-selected="false">
        Signatures <span class="badge" data-badge="signatures">0</span>
      </button>
    </div>

    <div class="tab-panel" data-panel="stories">
      <p class="muted small">Nothing here is public. Approving sets status to
      <code>approved</code> and the story appears immediately.</p>
      <div data-admin-stories><p class="news-loading">Loading&hellip;</p></div>
    </div>

    <div class="tab-panel" data-panel="social" hidden>
      <div class="admin-toolbar">
        <p class="muted small">Drafts generated by the cron worker. <strong>Nothing posts without
        approval here</strong>, and unapproved drafts expire after 48 hours rather than going out.</p>
        <button class="btn btn-sm btn-ghost" type="button" data-new-draft>Write a custom post</button>
      </div>
      <div data-admin-social><p class="news-loading">Loading&hellip;</p></div>
    </div>

    <div class="tab-panel" data-panel="signatures" hidden>
      <p class="muted small">Public-wall statements only. Hiding a statement does not remove the
      signature from the count.</p>
      <div data-admin-signatures><p class="news-loading">Loading&hellip;</p></div>
    </div>
  </div>
</section>`;

  return {
    title: 'Moderation',
    description: 'Internal moderation console.',
    path: '/admin/',
    body,
    scripts: ['/assets/js/admin.js'],
    bodyClass: 'is-admin',
  };
}
